### ISSUE TITLE
dmenu_extended_run does not open a file when using shortcut from i3

### ISSUE THREAD

**Issue by makkanx** [MarkHedleyJones/dmenu-extended#78]
When I use dmenu_extended_run from i3 with a shortcut it does not open a specific ods file.
If I use dmenu_extended_run from a teminal with python ~/dmenu-extended/dmenu_extended.py it opens that specific file. Another ods file opens with both methods. The two files are in the same location.

This one works
[10:08:00] $ xdg-mime query filetype zoner.ods
application/vnd.oasis.opendocument.spreadsheet

This one does not work. Just realized a difference UTF-8 issue maybe?
[10:08:12] $ xdg-mime query filetype räkning.ods
application/vnd.oasis.opendocument.spreadsheet

Yes, just verified it. Renamed räkning.ods to rakning.ods and now it opens. Is this a issue with i3 then?

**Comment by MarkHedleyJones** [comment]
Hi there,
No I don't think this is an issue with i3.
I've had trouble with UTF-8/Unicode paths in dmenu_extended in the past and this is something I don't understand well.
Unfortunately, I cannot recreate your issue on my computer.
When I create a spreadsheet called *räkning.ods*, dmenu_extended opens it fine.

Are you able to rename the file back to *räkning.ods* and test to see if it works again?
I know that sounds like a weird thing to do, but I'm wondering if it wasn't previously encoded using UTF-8. (See the final comment in #38 for more information if you're interested).

**Comment by makkanx** [comment]
I renamed the file back to räkning.ods and rebuilt the cache but it does still not open.

**Comment by MarkHedleyJones** [comment]
Hi there,
Sorry, I wrote the message yesterday not having properly read your description.
I believe I've found a solution to the problem now, which I have created a branch for - for you to test.
If you could test that branch and let me know if this solves your problem, that would be great.
If you're interested, the issue seems to be that when running the script via exec from i3, the output encoding of std is not set. On python2 this defaults to 'ascii', which fails when a unicode string is found. To test this you can either run dmenu from a terminal (which sets the encoding of stdout to 'utf-8') or run dmenu_extended with Python3 (which always handles strings as unicode), and it should always work.
Let me know if this solves your problem and I'll merge it into master.

**Comment by makkanx** [comment]
Yes, now it is working.
